name: project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  intl:
  awesome_dialog:
  fluttertoast: ^8.0.9
  firebase_auth:
  hive_flutter:
  hive:
  go_router:
  fl_chart:
  syncfusion_flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
