// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclTnM0BKfg5CBz0HARXZCg-rPBH_UCsE',
    appId: '1:618856351521:web:8595fe306fcab20e662060',
    messagingSenderId: '618856351521',
    projectId: 'borsa-takip-623c5',
    authDomain: 'borsa-takip-623c5.firebaseapp.com',
    storageBucket: 'borsa-takip-623c5.appspot.com',
    measurementId: 'G-MTY0JV4XQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwoS37beEhnOQNFy0I0ZAvWXWxhl0NiEQ',
    appId: '1:618856351521:android:fbf3ad3efc967595662060',
    messagingSenderId: '618856351521',
    projectId: 'borsa-takip-623c5',
    storageBucket: 'borsa-takip-623c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaPTDaQ-LhTAKZVWh_XNiijRC-dtLLQ4',
    appId: '1:618856351521:ios:9c4e5c421c546405662060',
    messagingSenderId: '618856351521',
    projectId: 'borsa-takip-623c5',
    storageBucket: 'borsa-takip-623c5.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAclTnM0BKfg5CBz0HARXZCg-rPBH_UCsE',
    appId: '1:618856351521:web:377e1ff7def30558662060',
    messagingSenderId: '618856351521',
    projectId: 'borsa-takip-623c5',
    authDomain: 'borsa-takip-623c5.firebaseapp.com',
    storageBucket: 'borsa-takip-623c5.appspot.com',
    measurementId: 'G-8LPXKFRSH8',
  );
}
